pipeline {
    agent any
    environment {
        AWS_CREDS = credentials('AWS_CREDS')
    }
    parameters {
        booleanParam(name: 'TF_INIT', defaultValue: false, description: 'Run terraform init')
        booleanParam(name: 'TF_IMPORT', defaultValue: false, description: 'Run terraform import')
      
        booleanParam(name: 'IMPORT_DB_INSTANCE', defaultValue: false, description: 'Import DB Instance?')
        string(name: 'DB_INSTANCE_ID', defaultValue: 'new-test-db-instance', description: 'DB Instance ID')
  
        booleanParam(name: 'IMPORT_SUBNET_GROUP', defaultValue: false, description: 'Import Subnet Group?')
        string(name: 'SUBNET_GROUP_NAME', defaultValue: 'example-subnet-group', description: 'Subnet Group Name')
  
        booleanParam(name: 'IMPORT_SECURITY_GROUP', defaultValue: false, description: 'Import Security Group?')
        string(name: 'SECURITY_GROUP_ID', defaultValue: 'sg-0fa56eb26a8b66557', description: 'Security Group ID')

        booleanParam(name: 'TF_PLAN', defaultValue: false, description: 'Run terraform plan')
        booleanParam(name: 'TF_APPLY', defaultValue: false, description: 'Run terraform apply')
        booleanParam(name: 'TF_DESTROY', defaultValue: false, description: 'Run terraform destroy')
        choice(name: 'TF_ACTION', choices: ['none', 'create', 'update'], description: 'Select the Terraform action')
    }
    stages {
        stage('Prerequisite') {
            steps {
                sh '''
                echo "==== Cleaning and Cloning Repo ===="
                rm -rf /var/lib/jenkins/workspace/rds_crud/*
                git clone https://github.com/priyanshusaineni/aws_rds_terraform.git
                '''
            }
        }
        stage('Terraform Init') {
            when {
                expression { params.TF_INIT }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                ls
                terraform init
                '''
            }
        }
        stage('Terraform Import') {
            when {
              expression { params.TF_IMPORT }
            }
            steps {
              script {
                if (params.IMPORT_DB_INSTANCE) {
                  sh '''
                  cd aws_rds_terraform
                  terraform import resource.aws_db_instance.test_db $DB_INSTANCE_ID
                  '''
                }
                if (params.IMPORT_SUBNET_GROUP) {
                  sh '''
                  cd aws_rds_terraform
                  terraform import resource.aws_db_subnet_group.example $SUBNET_GROUP_NAME
                  '''
                }
                if (params.IMPORT_SECURITY_GROUP) {
                  sh '''
                  cd aws_rds_terraform
                  terraform import resource.aws_security_group.scc_postgres_dbsg ${SECURITY_GROUP_ID}
                  '''
                }
              }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.TF_PLAN }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                terraform plan
                '''
            }
        }
        stage('Terraform Apply') {
            when {
                expression { params.TF_APPLY }
            }
            steps {
              script {
                if (params.TF_ACTION == 'create') {
                  // For create, run full terraform apply
                  sh '''
                    cd aws_rds_terraform
                    terraform apply --auto-approve
                  '''
                } else if (params.TF_ACTION == 'update') {
                  // For update, run terraform apply with targets

                  //Add other targets subnet_group and security_group if there are any changes in them
                  def targets = [
                    "aws_db_instance.test_db"
                  ]

                  def targetArgs = targets.collect { "-target=${it}" }.join(' ')
                  echo "Running terraform apply with targets: ${targetArgs}"
                  sh """
                    cd aws_rds_terraform
                    terraform apply ${targetArgs} --auto-approve
                  """
                } else {
                  error "Invalid TF_ACTION: ${params.TF_ACTION}. Must be 'create' or 'update'."
                }
              }
            }
        }

        stage('Terraform Destroy') {
          when {
            expression { params.TF_DESTROY }
          }
          steps {
            script {
              def targets = [
                "aws_db_instance.test_db"
              ]
              def targetArgs = targets.collect { "-target=${it}" }.join(' ')
              echo "Terraform destroy targets: ${targetArgs}"
              sh """
                cd aws_rds_terraform
                terraform destroy ${targetArgs} --auto-approve
              """
            }
          }
        }
    }
}
