pipeline {
    agent any
    environment {
        AWS_CREDS = credentials('AWS_CREDS')
    }
    parameters {
        booleanParam(name: 'TF_INIT', defaultValue: false, description: 'Run terraform init')
        booleanParam(name: 'TF_IMPORT', defaultValue: false, description: 'Run terraform import')
        booleanParam(name: 'TF_PLAN', defaultValue: false, description: 'Run terraform plan')
        booleanParam(name: 'TF_APPLY', defaultValue: false, description: 'Run terraform apply')
        booleanParam(name: 'TF_DESTROY', defaultValue: false, description: 'Run terraform destroy')
        choice(name: 'TF_ACTION', choices: ['create', 'update', 'none'], description: 'Select the Terraform action')
    }
    stages {
        stage('Prerequisite') {
            steps {
                sh '''
                echo "==== Cleaning and Cloning Repo ===="
                rm -rf /var/lib/jenkins/workspace/rds_crud/*
                git clone https://github.com/priyanshusaineni/aws_rds_terraform.git
                '''
            }
        }
        stage('Terraform Init') {
            when {
                expression { params.TF_INIT }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                terraform init
                '''
            }
        }
        stage('Terraform Import'){
            when {
                expression { params.TF_IMPORT }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                terraform import 'resource.aws_db_instance.test_db' new-test-db-instance
                '''
            }
        }
        stage('Terraform Plan') {
            when {
                expression { params.TF_PLAN }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                terraform plan
                '''
            }
        }
        stage('Terraform Apply') {
          when {
            expression { params.TF_APPLY }
          }
          steps {
            script {
              def targets = []
              if (params.TF_ACTION == 'create') {
                // resource blocks as targets
                targets = [
                  "aws_db_subnet_group.example",
                  "aws_security_group.scc_postgres_dbsg",
                  "aws_db_instance.test_db"
                ]
              } else if (params.TF_ACTION == 'update') {
                // data blocks as targets
                targets = [
                  "data.aws_db_subnet_group.selected",
                  "data.aws_security_group.selected",
                  "aws_db_instance.test_db"
                ]
              } else {
                error "Invalid TF_ACTION: ${params.TF_ACTION}. Must be 'create' or 'update'."
              }
              def targetArgs = targets.collect { "-target=${it}" }.join(' ')
              sh """
                cd aws_rds_terraform
                terraform apply ${targetArgs} --auto-approve
              """
            }
          }
        }


        stage('Terraform Destroy') {
            when {
                expression { params.TF_DESTROY }
            }
            steps {
                sh '''
                cd aws_rds_terraform
                terraform destroy --auto-approve
                '''
            }
        }
    }
}
